version: '3'
services:
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        entrypoint: redis-server --appendonly yes
        restart: always
        networks:
            - rocket
volumes:
    db-data:
networks:
    rocket:
        driver: bridge
